name: Download to registry
on: 
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry地址'
        required: true
        default: 'registry.cn-beijing.aliyuncs.com'
      repo:
        description: '仓库及标签 (格式: scope/repo:tag)'
        required: true
      file_list:
        description: '需要下载的文件 (格式：下载地址 文件名) 多个文件可以用分号或者\n隔开'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download to registry
      uses: ikrong/download-to-registry-action@main
      with:
        registry: ${{ github.event.inputs.registry }}
        credential: ${{ secrets.CREDENTIAL }}
        repo: ${{ github.event.inputs.repo }}
        file_list: ${{ github.event.inputs.file_list }}